language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t kosukemuramatsu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kosukemuramatsu/docker-react npm run test
